echo "Hello $1"
echo "Age : $2"
echo "City: $3"
echo "Total Arguments: $#"
echo "All arguments: $@"
for arg in "$*"
do echo "$arg"
done
echo "script name: $0"
echo "First argument: $1"
echo "Third argument: $3"
echo "Current Process ID: $$"
